server {
    listen 18100;
    server_name localhost;
    access_log off;
    client_max_body_size 16m;
    location / {
        proxy_pass http://backend:18100;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_read_timeout 120s;
    }
}
