"""initial schema

Revision ID: fde30f938654
Revises: 
Create Date: 2026-07-22 02:45:48.517410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde30f938654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    from migrations.schema_support import BASE_TABLES, legacy_metadata
    connection = op.get_bind()
    existing = set(sa.inspect(connection).get_table_names()) - {'alembic_version'}
    if not existing:
        # Frozen pre-SaaS schema, not db.create_all/current application metadata.
        legacy_metadata().create_all(connection)
    elif not BASE_TABLES.issubset(existing):
        raise RuntimeError('Incomplete legacy schema; migration requires an intact schema or an empty database')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
